export enum ErrorEnum {
    INVALID_CPF = 'INVALID_CPF',
    INVALID_EMAIL = 'INVALID_EMAIL',
    INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
    INVALID_USER = 'INVALID_USER',
    INVALID_ADDRESS = 'INVALID_ADDRESS',
    CITY_NOT_FOUND = 'CITY_NOT_FOUND',
    ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
    USER_NOT_FOUND = 'USER_NOT_FOUND'
}