export enum ErrorEnum {
    // Invalid properties values
    INVALID_CPF = 'INVALID_CPF',
    INVALID_EMAIL = 'INVALID_EMAIL',
    INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
    INVALID_USER = 'INVALID_USER',
    INVALID_ADDRESS = 'INVALID_ADDRESS',
    INVALID_STREET = 'INVALID_STREET',
    INVALID_NEIGHBOURHOOD = 'INVALID_NEIGHBOURHOOD',
    INVALID_CITY = 'INVALID_CITY',
    INVALID_FISTNAME = 'INVALID_FISTNAME',
    INVALID_LASTNAME = 'INVALID_LASTNAME',
    INVALID_PASSWORD = 'INVALID_PASSWORD',
    INVALID_NEW_PASSWORD = 'INVALID_NEW_PASSWORD',

    // Invalid properties rules
    INVALID_LENGTH = 'INVALID_LENGTH',
    INVALID_FORMAT = 'INVALID FORMAT',
    PROPERTY_CANNOT_BE_NULL = 'PROPERTY_CANNOT_BE_NULL',
    THE_NEW_PASSWORD_MUST_BE_FROM_THE_OLD_ONE = 'THE_NEW_PASSWORD_MUST_BE_FROM_THE_OLD_ONE',

    // Already exists
    CPF_ALREADY_EXISTS = 'CPF_ALREADY_EXISTS',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    PHONE_NUMBER_ALREADY_EXISTS = 'PHONE_NUMBER_ALREADY_EXISTS',

    // Required fields
    EMAIL_IS_REQUIRED = 'EMAIL_IS_REQUIRED',
    PASSWORD_IS_REQUIRED = 'PASSWORD_IS_REQUIRED',
    NEW_PASSWORD_IS_REQUIRED = 'NEW_PASSWORD_IS_REQUIRED',

    // Authentication
    UNAUTHORIZED = 'UNAUTHORIZED',
    EXPIRED_TOKEN = 'EXPIRED_TOKEN',
    INVALID_TOKEN = 'INVALID_TOKEN',
    REFRESH_TOKEN_IS_REQUIRED = 'REFRESH_TOKEN_IS_REQUIRED',

    // Not found
    CITY_NOT_FOUND = 'CITY_NOT_FOUND',
    ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
}